version: '3'

services:
  # Contenedor de la base de datos PostgreSQL
  db:
    image: postgres:13
    container_name: mi-proyecto-db
    environment:
      POSTGRES_DB: mi_basededatos
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_contraseña
    ports:
      - "5432:5432"
    networks:
      - mi-red

  # Contenedor de la aplicación Django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-proyecto-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mi-red

networks:
  mi-red: